name: CMake SKSE Setup

on:
  push:
    branches: [ "main" ]

env:
  VCPKG_ROOT: ${{ github.workspace }}\vcpkg

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup cmake
      uses: lukka/get-cmake@latest
    
    - name: Restore from cache and setup vcpkg executable and data files.
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: '${{ github.workspace }}\vcpkg.json'

    - name: CMake Project Version
      id: cmake_version
      uses: DarwinInnovation/cmake-project-version-action@v1.0
      with:
        path: '${{ github.workspace }}'
            
        
    - name: Configure and Run CMake Preset for "Debug" preset
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'Debug'
        buildPreset: 'Debug'

    - name: Configure and Run CMake Preset for "Release" preset
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'Release'
        buildPreset: 'Release'
      
    - name: Deploy Aritfact
      uses: actions/upload-artifact@v4.3.3
      with:
        path: ${{github.workspace}}/contrib/Artifact/${{ steps.cmake_version.outputs.project }}_${{ steps.cmake_version.outputs.version }}.7z

    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{github.workspace}}/contrib/Artifact/${{ steps.cmake_version.outputs.project }}_${{ steps.cmake_version.outputs.version }}.7z
        overwrite: true
        tag: ${{ github.ref }}
        release_name: Release
        target_commit: main
